#
###################################
# Site wide configuration
####################################
#
title: WahlBilanz.de
email:
description: Informationen zum 18. Deutschen Bundestag, Legislaturperiode 2013-2017.
url: # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Berlin
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:year/:month/:title/
gems: ["jekyll-paginate", "jekyll-sitemap"]
exclude: ["README.md"]
paginate: 10
paginate_path: "page:num"

url: https://wahlbilanz.de

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


#
###################################
# Site Owner configuration
####################################
#
owner:
  name: WahlBilanz.de
  avatar: wahl-logo.jpg
  job: "News.Daten.Wissenswertes."
  bio: "Informationen zum 18. Deutschen Bundestag. Wer hat was wann und wie entschieden? <a href='/2017/06/und-los/'>Wieso?</a>"
  email:
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username


authors:
    binfalse:
        display_name: Martin Scharm
        link: https://binfalse.de
        about: Bioinformatiker und System Administrator an der Uni Rostock.
        twitter: binfalse
        github: binfalse
        bitbucket: binfalse
        facebook: 
        image: /img/profiles/binfalse.jpg
    tomthe:
        display_name: Tom Theile
        link: 
        about: 
        twitter: 
        github: tomthe
        bitbucket: tomthe
        facebook: 
        image: 
